using System.Diagnostics.CodeAnalysis;

namespace RazorSlices;

/// <summary>
/// Defines a strongly-typed Razor Slice that can be created via <see cref="RazorSliceFactory"/>.
/// </summary>
/// <typeparam name="TModel">The model type.</typeparam>
/// <remarks>
/// This type is used by the types generated by the Razor Slices source generator. You should not need to interact with this type directly in your project.
/// </remarks>
public sealed class SliceDefinition<TModel> : SliceDefinition
{
    private Func<TModel, RazorSlice<TModel>>? _createSlice;

    /// <summary>
    /// Creates a new instance of <see cref="SliceDefinition{TModel}"/>.
    /// </summary>
    /// <param name="sliceType">The type of the slice.</param>
    public SliceDefinition(
        [DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
        Type sliceType)
        : base(sliceType, RazorSliceFactory.GetSliceFactory<TModel>)
    {
    }

    /// <inheritdoc />
    private protected override void OnFactoryCreated(Delegate factory)
    {
        _createSlice = (Func<TModel, RazorSlice<TModel>>)factory;
    }

    /// <summary>
    /// Creates a new instance of the slice this definition represents with the specified model.
    /// </summary>
    /// <param name="model">The model for the slice.</param>
    /// <returns>The slice instance.</returns>
    public RazorSlice<TModel> CreateSlice(TModel model) => _createSlice!(model);
}
