name: Release

on:
  workflow_dispatch:
    inputs:
      runId:
        description: The run ID of the CI workflow to release NuGet artifacts from
        required: true
        type: string

env:
  PACKAGE_ID: RazorSlices

jobs:
  push-package:
    name: Release
    runs-on: ubuntu-latest
    environment: nuget.org
    permissions:
      actions: read
      contents: write
      id-token: write
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true

    steps:
      - name: Get workflow run commit SHA
        id: workflowsha
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          runDetails=$(gh api "repos/${{ github.repository }}/actions/runs/${{ inputs.runId }}")
          conclusion=$(echo "$runDetails" | jq -r '.conclusion')
          if [ "$conclusion" != "success" ]; then
            echo "Workflow run ${{ inputs.runId }} concluded with '$conclusion', expected 'success'."
            exit 1
          fi

          sha=$(echo "$runDetails" | jq -r '.head_sha')
          echo "sha=$sha" >> "$GITHUB_OUTPUT"

      - name: Download workflow run artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ inputs.runId }}
          name: nupkg
          path: .
      
      - name: Get package version into an environment variable
        run: |
          _filepath="$(find ./ship -iname $PACKAGE_ID.*.nupkg)"
          _filename="${_filepath##*/}"
          _pkgname="${_filename%.*}"
          _version="${_pkgname##$PACKAGE_ID.}"
          echo "PACKAGE_VERSION=${_version}" >> $GITHUB_ENV
          echo "PACKAGE_FILEPATH=${_filepath}" >> $GITHUB_ENV

      - name: Verify package version doesn't exist
        run: |
          _packageId="$PACKAGE_ID"
          _packageVersion="$PACKAGE_VERSION"
          _packageIdLower="${_packageId,,}"
          _packageUrl="https://api.nuget.org/v3/registration5-semver1/${_packageIdLower}/${_packageVersion}.json"
          echo "Checking for existing package at ${_packageUrl}"
          _statusCode=$(curl -s -o /dev/null -I -w '%{http_code}' "${_packageUrl}")
          if [ $_statusCode == "200" ]; then
            echo "The package ${_packageId} with version ${_packageVersion} already exists on nuget.org"; exit 1
          elif [ $_statusCode == "404" ]; then
            echo "Confirmed package ${_packageId} with version ${_packageVersion} does not already exist on nuget.org"
          else
            echo "Unexpected status code ${_statusCode} received from nuget.org"; exit 1
          fi

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          args=(--target "${{ steps.workflowsha.outputs.sha }}" --generate-notes --draft)
          if [[ "$PACKAGE_VERSION" == *-* ]]; then
            args+=(--prerelease)
          fi

          gh release create "v$PACKAGE_VERSION" "${args[@]}" --repo "${{ github.repository }}"

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0

      - name: NuGet login (OIDC)
        id: nuget-login
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
        with:
          user: ${{ github.repository_owner }}

      - name: Push to nuget.org
        run: dotnet nuget push "$PACKAGE_FILEPATH" --api-key ${{ steps.nuget-login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
